= opennms-nexus

Repository to setup a nexus maven to increase build time of OpenNMS.

NOTE: The configured nexus only mirrors the OpenNMS bits of the official OpenNMS maven repository.
For all other 3rd party repositories the official repositories are used.

== How To Use

1. Download the latest Nexus tar.gz from link:http://www.sonatype.org/nexus/archived/[] to `/opt`
2. Untar the downloaded archive: `tar -xvf nexus-X.X.X`
3. Create a working directory `mkdir -p /opt/sonatype-work`
4. Create the nexus conf directory: `mkdir -p sonatype-work/nexus/conf`
5. Copy the `nexus/nexus.xml` file from here to the `sonatype-work/nexus/conf/` directory.
6. Copy the `nexus/wrapper.conf` file from here to `nexus/bin/jsw/conf/` directory and may modify it to your needs.
7. Copy the `nexus/truststore.jks` file from here to `/etc/ssl/certs/java`directory.
8. Start nexus.
9. Copy `m2-home/settings.xml` to `~/.m2/` if you don't have one already. If you do already have one, copy the mirrors section to your existing config.

== TODO
- Add tasks as maven.opennms.org does to ensure integrity
- maybe we should just proxy maven.opennms.org instead of using the "real" repositories.
